name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 8.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.14.0
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: www
          BUILD_SCRIPT: npm install && npm run build
